import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta
               name='description'
               content='Generated by create next app'
            />
            <meta
               name='viewport'
               content='width=device-width, initial-scale=1'
            />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <section className=' bg-candle bg-cover h-screen bg-no-repeat bg-center'>
            <div className='grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12'>
               <div className='mr-auto place-self-center lg:col-span-7'>
                  <h1 className='max-w-2xl mb-4 text-4xl text-white font-extrabold tracking-tight leading-none md:text-5xl xl:text-6xl'>
                     Under Construction
                  </h1>
               </div>
            </div>
         </section>
      </>
   );
}
